### PR TITLE
Handle the feedback by the reviewers

### PR DESCRIPTION
**Pull request by rogierslag**
@sback @Xyclade I have addressed most of the feedback

This caused parts to be eliminated, since we did more specific research (not sure why sentistrength wasn't in the course version either actually)

Can you check whether you both agree on most of the changes?

Things I will address in another PR:
- Use words as _surprisingly_ less often

### CODE REVIEW

**Comment by Xyclade** [comment]
I agree! nice work :+1:

**Comment by Xyclade** [comment]
We have to hand this in today though, So can you comment on this @sback

**Comment by sback** [comment]
Doing it tomorrow morning; we have until Mar 30, 23:59 AoE

**Comment by sback** [comment]
Good for me, merging.

**Pull request merged**
